package vista;

import excepcion.Excepcion;
import handler.Manager;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Equipo;
import modelo.Juego;
import modelo.Jugador;
import modelo.Oferta;

public class MenuEquipo extends javax.swing.JFrame {

    public MenuEquipo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCrearOferta = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnVerJugadores = new javax.swing.JButton();
        btnVerCandidatos = new javax.swing.JButton();
        btnBorrarOferta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MENU EQUIPO");

        btnCrearOferta.setText("Crear Oferta");
        btnCrearOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearOfertaActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnPerfil.setText("Perfil");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        btnVerJugadores.setText("Ver Jugadores");
        btnVerJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerJugadoresActionPerformed(evt);
            }
        });

        btnVerCandidatos.setText("Ver Candidatos");
        btnVerCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCandidatosActionPerformed(evt);
            }
        });

        btnBorrarOferta.setText("Borrar Ofertas");
        btnBorrarOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarOfertaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBorrarOferta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrearOferta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerCandidatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCrearOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerCandidatos)
                .addGap(18, 18, 18)
                .addComponent(btnBorrarOferta)
                .addGap(18, 18, 18)
                .addComponent(btnVerJugadores)
                .addGap(18, 18, 18)
                .addComponent(btnPerfil)
                .addGap(18, 18, 18)
                .addComponent(btnLogOut)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearOfertaActionPerformed
        try{
            ArrayList<Juego> juegos = Manager.bbdd.returnJuegos();
            if(juegos.isEmpty()){
                throw new Excepcion(Excepcion.errorInserts);
            }
            CrearOferta crearOferta = new CrearOferta(this, true);
            crearOferta.setTitle("Crear Oferta");
            crearOferta.setLocationRelativeTo(null);
            crearOferta.setVisible(true);
        }catch (SQLException|Excepcion ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearOfertaActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        Login login = new Login();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        PerfilEquipo perfilEquipo = new PerfilEquipo(this, true);
        perfilEquipo.setTitle("Perfil");
        perfilEquipo.setLocationRelativeTo(null);
        perfilEquipo.setVisible(true);
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnVerJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerJugadoresActionPerformed
        //Comprobamos que exista algun jugador
        try{
            ArrayList<Jugador> jugadores = Manager.bbdd.returnJugadores();
            if(jugadores.isEmpty()){
                throw new Excepcion(Excepcion.noHayNingunJugador);
            }
            VerJugadores verJugadores = new VerJugadores(this, true);
            verJugadores.setTitle("Jugadores");
            verJugadores.setLocationRelativeTo(null);
            verJugadores.setVisible(true);
        }catch (SQLException|Excepcion|ParseException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVerJugadoresActionPerformed

    private void btnVerCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCandidatosActionPerformed
        //Comprobamos que el equipo haya creado alguna oferta
        try{
            Equipo e = Manager.bbdd.returnEquipo(Manager.getUsuario());
            ArrayList<Oferta> ofertas = Manager.bbdd.returnOfertasFiltradas(e.getIdequipo(), -1);
            if(ofertas.isEmpty()){
                throw new Excepcion(Excepcion.noHasCreadoNingunaOferta);
            }
            VerCandidatosOfertas verCandidatosOfertas = new VerCandidatosOfertas(this, true);
            verCandidatosOfertas.setTitle("Candidatos");
            verCandidatosOfertas.setLocationRelativeTo(null);
            verCandidatosOfertas.setVisible(true);
        }catch (SQLException|Excepcion|ParseException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVerCandidatosActionPerformed

    private void btnBorrarOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarOfertaActionPerformed
        //Comprobamos que el equipo haya creado alguna oferta
        try{
            Equipo e = Manager.bbdd.returnEquipo(Manager.getUsuario());
            ArrayList<Oferta> ofertas = Manager.bbdd.returnOfertasFiltradas(e.getIdequipo(), -1);
            if(ofertas.isEmpty()){
                throw new Excepcion(Excepcion.noHasCreadoNingunaOferta);
            }
            BorrarOferta borrarOferta = new BorrarOferta(this, true);
            borrarOferta.setTitle("Borrar Oferta");
            borrarOferta.setLocationRelativeTo(null);
            borrarOferta.setVisible(true);
        }catch (SQLException|Excepcion|ParseException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBorrarOfertaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarOferta;
    private javax.swing.JButton btnCrearOferta;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnVerCandidatos;
    private javax.swing.JButton btnVerJugadores;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
